FROM python:3.6
LABEL maintainer="olasodeadeyemi@gmail.com"
LABEL description="Python 3 microservice support discount app UI."

## CREATE DISCOUNT APPLICATION BACKEND

WORKDIR /backend

COPY ./backend /backend/

RUN pip install -r requirements.txt

# Start processes
CMD ["flask", "run", "--host=0.0.0.0"]
