version: '3'
services:
  discount_app_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    container_name: discount_app_frontend
    links:
      - 'discount_app_backend:backend'
    depends_on:
      - discount_app_backend

  discount_app_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    ports:
      - '5000:5000'
    container_name: discount_app_backend
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - discount_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 10s
      retries: 5

volumes:
  discount_db_data:
