version: '3'
services:
  discount_app_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    links:
      - discount_app_backend
    ports:
      - '3000:3000'
    container_name: discount_app_frontend

  discount_app_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    links:
      - postgres
    ports:
      - '5000:5000'
    container_name: discount_app_backend

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 10s
      retries: 5
